version: 0.2
        
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - java --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 327229172692.dkr.ecr.us-east-1.amazonaws.com
      - docker pull postgres:12
      - docker pull 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.oracle_graalvm:latest
      - docker tag 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.oracle_graalvm:latest oracle/graalvm-ce:20.3.0-java11
      - docker tag 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.oracle_graalvm:latest oracle/graalvm-ce:latest
      - docker images
  build:
    commands:
      - docker images
      - ./gradlew build
      - ./gradlew dockerBuild
      - docker tag miiingle-net-user-api:latest 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.user_api:latest
      - ./gradlew dockerBuildNative
      - docker tag miiingle-net-user-api:latest 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.user_api:latest-native
      - docker images | grep miiingle
  post_build:
    commands:
      - docker push 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.user_api:latest
      - docker push 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.user_api:latest-native