version: 0.2
        
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - java --version
      - docker pull postgres:12
      - docker pull oracle/graalvm-ce:20.3.0-java11
      - docker images
  build:
    commands:
      - ./gradlew build
      - ./gradlew dockerBuild
      - ./gradlew dockerBuildNative
      - docker images | grep miiingle