version: 0.2
        
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - java --version
      - $(aws ecr get-login --no-include-email)
      - docker pull postgres:12
      - docker pull ghcr.io/graalvm/graalvm-ce:java11-21.0.0
      - docker pull gcr.io/distroless/cc-debian10
      - docker pull amazoncorretto:11
      - docker pull $MISC_REPOSITORY_URL:jmeter-user-api
      - docker images
  build:
    commands:
      - ./gradlew clean test
      - docker build . -t $CONTAINER_REPOSITORY_URL:latest -t $CONTAINER_REPOSITORY_URL:$CODEBUILD_BUILD_NUMBER
      - docker build . -f DockerfileNative -t $CONTAINER_REPOSITORY_URL:latest-native -t $CONTAINER_REPOSITORY_URL:$CODEBUILD_BUILD_NUMBER-native
      - docker run -d -p 8080:8080 $CONTAINER_REPOSITORY_URL:latest-native
      - docker run --network="host" $MISC_REPOSITORY_URL:jmeter-user-api
      - docker images | grep miiingle
  post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URL:$CODEBUILD_BUILD_NUMBER
      - docker push $CONTAINER_REPOSITORY_URL:$CODEBUILD_BUILD_NUMBER-native
      - docker push $CONTAINER_REPOSITORY_URL:latest
      - docker push $CONTAINER_REPOSITORY_URL:latest-native
