version: 0.2
        
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - java --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 327229172692.dkr.ecr.us-east-1.amazonaws.com
      - docker pull postgres:12
      - docker pull ghcr.io/graalvm/graalvm-ce:java11-21.0.0
      - docker pull gcr.io/distroless/cc-debian10
      - docker pull amazoncorretto:11
      - docker images
  build:
    commands:
      - ./gradlew clean test
      - docker build . -t 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.user_api:latest
      - docker build . -f DockerfileNative -t 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.user_api:latest-native
      - docker images | grep miiingle
  post_build:
    commands:
      - docker push 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.user_api:latest
      - docker push 327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.user_api:latest-native