version: 0.2
        
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - java --version
      - docker pull postgres:12
      - docker images
# TODO:
# (a) login to dockerhub or
# (b) host this ourselves - need to tell dockerBuildNative how (or hack using image pull and tag)
#   https://docs.aws.amazon.com/codebuild/latest/userguide/sample-private-registry.html
#      - docker pull oracle/graalvm-ce:20.3.0-java11
  build:
    commands:
      - ./gradlew build
      - ./gradlew dockerBuild
      - ./gradlew dockerBuildNative
      - docker images | grep miiingle
