version: '3.7'
services:
  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
    ports:
      - 5432:5432
#  mysql:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'db'
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#      MYSQL_ROOT_PASSWORD: ''
#    ports:
#      - 3306:3306