version: '3.7'
services:
  postgres:
    image: postgres:11.10-alpine
    environment:
      POSTGRES_USER: testfull
      POSTGRES_PASSWORD: testfullpass123
    ports:
      - 5432:5432
  liquibase:
    image: miiingle-user-api-liquibase:latest
    environment:
      URL: 'jdbc:postgresql://postgres:5432/postgres?currentSchema=public'
      USERNAME: testfull
      PASSWORD: testfullpass123
    depends_on:
      - postgres
      - zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
  user-api:
    image: '327229172692.dkr.ecr.us-east-1.amazonaws.com/miiingle.net.user_api:latest-native'
    depends_on:
      - liquibase
    environment:
      CLIENT_EMAIL: logging
      TRACING_ZIPKIN_HTTP_URL: http://zipkin:9411
      DATASOURCES_DEFAULT_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=public
      DATASOURCES_DEFAULT_USERNAME: testfull
      DATASOURCES_DEFAULT_PASSWORD: testfullpass123
      LOGGER_LEVEL_ROOT: DEBUG
    ports:
      - 8080:8080