version: '3.7'
services:

  postgres:
    image: postgres:11.10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'secret'
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 10

  liquibase:
    image: miiingle-user-api-liquibase:latest
    environment:
      URL: 'jdbc:postgresql://postgres:5432/postgres?currentSchema=public'
      USERNAME: postgres
      PASSWORD: 'secret'
    depends_on:
      postgres:
        condition: service_healthy

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411

  postgres_keycloak:
    image: postgres:11.10-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_secret
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 15

  keycloak:
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    image: quay.io/keycloak/keycloak:12.0.4
    ports:
      - 8081:8080
    healthcheck:
      test: [ "CMD-SHELL", "curl localhost:8080/auth/realms/master --fail" ]
      interval: 30s
      timeout: 5s
      retries: 15
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak
      DB_DATABASE: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak_secret
      PROXY_ADDRESS_FORWARDING: "true"