version: '3.7'
services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'secret'
    ports:
      - 5432:5432
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411