micronaut:
  application:
    name: miiingleNetUserApi
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  server:
    cors:
      enabled: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.entity-scan.packages: 'net.miiingle.user.api.client.persistence.data'

# determines the kind of email client that we are wiring: ses, logging, error
client.email: logging