micronaut:
  application:
    name: 'user-api'
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: 'http://localhost:8081/auth/realms/master/protocol/openid-connect/certs'
  server:
    cors:
      enabled: true
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'secret'
    schema-generate: NONE
    dialect: POSTGRES