micronaut:
  application:
    name: 'user-api'
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: "${KEYCLOAK_PROTOCOL:http}://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8081}/auth/realms/${KEYCLOAK_REALM:master}/protocol/openid-connect/certs"
  server:
    cors:
      enabled: true
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'secret'
    schema-generate: NONE
    dialect: POSTGRES

tracing:
  zipkin:
    http:
      url: http://localhost:9411
    enabled: true
    sampler:
      probability: 1